default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: admin
  pool: 5
  timeout: 5000
  host: <%= ENV['POSTGRES_HOST'] || 'localhost' %>
development:
  <<: *default
  database: ryan_development
test:
  <<: *default
  database: ryan_test
production:
  <<: *default
  database: ryan_production